# yum and service modules with sudo access
# using selinux module to set the target to permissive mode

---
- hosts: web
  become: yes
  vars: 
    username: ravi
    doc_root: /var/www/html
  tasks:

# This task will set the SELinux to Permissive mode
  - name: Put SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive

# This task will install apache http server
  - name: Install Apache
    yum:
      name: httpd
      state: present

# This task will start apache http server
  - name: Start Apache
    service:
      name: httpd 
      state: started 
      enabled: yes

# This will copy site file
  - name: Copy index template from templates
    template: 
      src: 23/templates/index.html 
      dest: "{{ doc_root }}"

# This task will copy custom httpd.conf file to /etc/httpd/conf/httpd.conf
# This will also call the hander Restart Apache
  - name: Copy apache config with port 80 defined
    copy: 
      src: 13/httpd.conf 
      dest: /etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache


  handlers: 
# This handler will restart apache http server
  - name: Restart Apache
    service:
      name: httpd 
      state: restarted

